name: cabofind
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter    
  #Funciones      

  firebase_messaging: ^5.1.5
  http: any
  path_provider: ^1.6.9
  dio: ^3.0.8
  url_launcher: any
  flutter_swiper : ^1.1.6
  font_awesome_flutter: any
  shared_preferences: ^0.5.7+3 
  #Video
  flutter_youtube: "^2.0.0"
  #chewie: ^0.9.8+1  
  #flutter_youtube_view: ^1.1.6  
  #flutube: 0.8.3
  #youtube_player_flutter: ^7.0.0+1
  #video_player: ^0.10.5  
  #Dispositivos
  device_info: ^0.4.2+4
  devicelocale: ^0.2.1
  #Autentificacion
  provider: ^4.0.2
  flutter_facebook_login: ^3.0.0  
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.3.0
  #Navegacionydiseño
  flutter_staggered_grid_view: "^0.3.0"  
  ff_navigation_bar: ^0.1.5
  dropdown_menu: ^1.1.1
  dropdownfield: ^1.0.3  
  carousel_pro: ^1.0.0
  carousel_slider: ^1.4.1  
  fluttertoast: ^3.1.3  
  flutter_web_browser: ^0.11.0  
  #Localizacion
  google_maps_flutter: ^0.5.21
  google_map_polyline: 
  location: ^2.3.5
  permission:  
  #Shopping
  #flutter_google_pay: ^0.1.4
  flutter_datetime_picker: ^1.3.8
  intl: ^0.16.0  
  qr_flutter: ^3.2.0
  dotted_border: ^1.0.5
  #encrypt: ^4.0.2
  #expand_widget: ^0.2.0+2
  expandable: ^4.1.4
  share: ^0.6.4+3
  barcode_scan: ^3.0.1  
  stripe_native: ^1.2.3
 
  #flutter_conekta: ^1.0.7+1
  #expandable_widget: ^1.0.5
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1
  cached_network_image: ^2.2.0+1
  awesome_dialog: ^1.1.3
  #audioplayers: ^0.15.1
  clippy_flutter: ^1.1.1
  

  
  #flutter_localizations: 
dependency_overrides: 

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/icon/cabofind.png"
 adaptive_icon_background: "assets/cabofind.png"


 

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
  - android/assets/images/
  - assets/
  - assets/map_style1.txt
  - 

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
      - family:  Banderasicon
        fonts:
        - asset: fonts/Banderasicon.ttf