/// Flutter icons Banderasicon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Banderasicon
///      fonts:
///       - asset: fonts/Banderasicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Banderasicon {
  Banderasicon._();

  static const _kFontFam = 'Banderasicon';

  static const IconData i001_mexico = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData i004_united_states_1 = const IconData(0xe803, fontFamily: _kFontFam);
}
